### ISSUE TITLE
Constans in @TestWith anotation

### ISSUE THREAD

**Issue by storytime** [piotrturski/zohhak#8]
Hi
When, I'm run test in such way http://pastebin.com/zvK5xrhn all is ok.
But I'm not possible to run it in such way http://pastebin.com/3hhH2wzd (2)

Can you please advice how to use value form constants(2) etc .

**Comment by piotrturski** [comment]
it has nothing to do with zohhak. it's java's limitation. in the below code, `arg` is NOT a constant because you can still change its content. therefore it doesn't compile.
```java
private static final String[] arg = {"0", "1", "2", "3", "4", "5","6","7"};
    @TestWith(arg)
    public void testServiceClick(int i) {}
```
AFAIK there is no way to define an array once and pass it to multiple annotations. therefore you can't do that in zohhak. if you want to share parameters between tests you should use different tool. there are runners that let you use dataproviders or jasmine-like testing
